### ISSUE TITLE
Needs testing on Windows

### ISSUE THREAD

**Issue by cznic** [cznic/memory#1]
Hi @steffengy, may I please ask you to run `go test` on windows_{amd64,386}? Thank you in advance.

**Comment by cznic** [comment]
Updates cznic/sqlite#12.

**Comment by steffengy** [comment]
Running `go test` in `cznic/memory` just PASSes.
Anything else you'd like me to try or any output you need?

**Comment by cznic** [comment]
> Running go test in cznic/memory just PASSes.

Good! Thanks for testing.

> Anything else you'd like me to try or any output you need?

Thanks, no, that's all I wanted to know before switching CRT to use this package.

**Comment by cznic** [comment]
Tests no more pass on Windows, reopening. See: https://github.com/cznic/sqlite/issues/12#issuecomment-308130854

**Comment by cznic** [comment]
Fixed. Confirmed here: https://github.com/cznic/sqlite/issues/12#issuecomment-308143282.
